config/routes.rb
Rails.application.routes.draw do
  
  root to: "users#index"
  
  get '/users' => 'users#index', as: 'users'
  get '/users/create' => 'users#create', as: 'create_user'
  get '/users/email' => 'users#email', as: 'email_user'
  get '/users/login/:user_guid' => 'users#login', as: 'login_user'
  get '/users/logout' => 'users#logout', as: 'logout_user'
  get '/users/edit/:user_id' => 'users#edit', as: 'edit_user'
  get '/users/modify/:user_id' => 'users#modify', as: 'modify_user'
  
  get '/info' => 'info#index', as: 'info'
  
  get '/comparitor' => 'comparitor#index', as: 'comparitor'
  
  get '/studies' => 'studies#index', as: 'studies'
  get '/studies/search' => 'studies#search', as: 'search_study'
  get '/studies/new' => 'studies#new', as: 'new_study'
  get '/studies/manage' => 'studies#manage', as: 'manage_study'
  get '/studies/duplicate' => 'studies#duplicate', as: 'duplicate_study'
  get '/studies/show/:study_id' => 'studies#show', as: 'show_study'
  get '/studies/edit/:study_id' => 'studies#edit', as: 'edit_study'
  get '/studies/rename/:study_id' => 'studies#rename', as: 'rename_study'
  get '/studies/activate/:study_id/:n_way' => 'studies#activate', as: 'activate_study'
  get '/studies/publicize/:study_id' => 'studies#publicize', as: 'publicize_study'
  get '/studies/hide/:study_id' => 'studies#hide', as: 'hide_study'
  get '/studies/destroy/:study_id' => 'studies#destroy', as: 'destroy_study'
  get '/studies/add_to/:study_id' => 'studies#add_to', as: 'add_to_study'
  get '/studies/import_to/:study_id' => 'studies#import_to', as: 'import_to_study'
  get '/studies/remove_from/:study_id' => 'studies#remove_from', as: 'remove_from_study'
  get '/studies/export_items/:study_id' => 'studies#export_items', as: 'export_items_study'
  get '/studies/export_comparisons/:study_id' => 'studies#export_comparisons', as: 'export_comparisons_study'
  get '/studies/export_both/:study_id' => 'studies#export_both', as: 'export_both_study'
  
  get '/comparisons/assign/:study_id' => 'comparisons#assign', as: 'assign_comparison'
  get '/comparisons/show_two_way/:item_id1/:item_id2' => 'comparisons#show_two_way', as: 'show_two_way_comparison'
  get '/comparisons/show_three_way/:item_id1/:item_id2/:item_id3' => 'comparisons#show_three_way', as: 'show_three_way_comparison'
  get '/comparisons/two_way/:item_id1/:rank1/:item_id2/:rank2' => 'comparisons#two_way', as: 'two_way_comparison'
  get '/comparisons/three_way/:item_id1/:item_id2/:item_id3' => 'comparisons#three_way', as: 'three_way_comparison'
  get '/comparisons/undo/:study_id' => 'comparisons#undo', as: 'undo_comparison'
  
  get '/keyboard' => 'keyboard#index', as: 'keyboard'
  
  get '*path' => redirect("/")
  

end

app/models/comparison.rb
class Comparison < ActiveRecord::Base
  validates :user_id, presence: true
  validates :study_id, presence: true
  validates :time, presence: true
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  before_action :authenticate
  
  # If user is not properly authenticated, 
  # e.g., if the user has no GUID, 
  # or if the GUID does not match the user ID in the session,
  # then log the user out.
  def authenticate
    begin
      if !session[:user_guid]
        redirect_to(root_path)
      elsif session[:user_guid] != User.find_by(id: session[:user_id].to_i).guid
        redirect_to(logout_user_path)
      end
    rescue
      redirect_to(logout_user_path)
    end
  end
  
  # If authenticated, redirect to comparison view for 
  # two or three random items in specified study.
  # Also, if user has recently compared these items, say so.
  def assign
    begin
      study = Study.find(params[:study_id])
      @items = Item.where(study_id: study.id)
      
      if @items.size < study.n_way
        redirect_to(studies_path)
        return
      end
      
      if study.n_way == 3
        item_id1 = rand(@items.size)
        item_id2 = rand(@items.size)
        while item_id1 == item_id2
          item_id2 = rand(@items.size)
        end
        item_id3 = rand(@items.size)
        while item_id1 == item_id3 || item_id2 == item_id3
          item_id3 = rand(@items.size)
        end
        
        comparisons = []
        Comparison.where(user_id: session[:user_id], study_id: params[:study_id]).each do |c|
          rank1 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id1].id)
          rank2 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id2].id)
          rank3 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id3].id)
          if rank1 && rank2 && rank3
            comparisons << c
          end        
        end
        c = comparisons.max
        if c
          rank1 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id1].id).rank
          rank2 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id2].id).rank
          rank3 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id3].id).rank
          
          if rank1 > rank2
            temp = rank1
            rank1 = rank2
            rank2 = temp
            
            temp = item_id1
            item_id1 = item_id2
            item_id2 = temp
          end
          
          if rank2 > rank3
            temp = rank2
            rank2 = rank3
            rank3 = temp
            
            temp = item_id2
            item_id2 = item_id3
            item_id3 = temp
          end
          
          if rank1 > rank2
            temp = rank1
            rank1 = rank2
            rank2 = temp
            
            temp = item_id1
            item_id1 = item_id2
            item_id2 = temp
          end
          
          notice = "You recently ranked #{@items[item_id1].name} "
          if rank1 < rank2
            notice = notice + "above "
          else
            notice = notice + "the same as "
          end
          notice = notice + "#{@items[item_id2].name}, which you ranked "
          if rank2 < rank3
            notice = notice + "above "
          else
            notice = notice + "the same as "
          end
          notice = notice + "#{@items[item_id3].name}."
          flash[:notice] = notice
        end
        
        redirect_to(show_three_way_comparison_path(@items[item_id1].id, @items[item_id2].id, @items[item_id3].id))
      else
        item_id1 = rand(@items.size)
        item_id2 = rand(@items.size)
        while item_id1 == item_id2
          item_id2 = rand(@items.size)
        end
      
        comparisons = []
        Comparison.where(user_id: session[:user_id], study_id: params[:study_id]).each do |c|
          rank1 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id1].id)
          rank2 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id2].id)
          if rank1 && rank2
            comparisons << c
          end        
        end
        c = comparisons.max
        if c
          rank1 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id1].id).rank
          rank2 = Rank.find_by(comparison_id: c.id, item_id: @items[item_id2].id).rank
          
          if rank1 > rank2
            temp = rank1
            rank1 = rank2
            rank2 = temp
            
            temp = item_id1
            item_id1 = item_id2
            item_id2 = temp
          end
          
          if rank1 != rank2
            flash[:notice] = "You recently ranked #{@items[item_id1].name} above #{@items[item_id2].name}."
          else
            flash[:notice] = "You recently said you were not sure whether #{@items[item_id1].name} or #{@items[item_id2].name} is better."
          end
        end
        
        redirect_to(show_two_way_comparison_path(@items[item_id1].id, @items[item_id2].id))
      end
    rescue
      redirect_to(studies_path)
    end
  end
  
  # If authenticated, and if items are valid and study is active,
  # show comparison view for two items.
  def show_two_way
    begin
      @item1 = Item.find(params[:item_id1])
      @item2 = Item.find(params[:item_id2])
      study = Study.find(@item1.study_id)
      
      if study.n_way != 2
        redirect_to(studies_path)
        return
      end
    
      if @item1 == @item2 || @item1.study_id != @item2.study_id || study.active == false
        redirect_to(studies_path)
        return
      end
    
      @study_id = study.id
      @study_name = study.name
      @ncomparisons = Comparison.where(user_id: session[:user_id], study_id: study.id).size
    rescue
      redirect_to(studies_path)
    end
  end
  
  def show_three_way
    begin
      @item1 = Item.find(params[:item_id1])
      @item2 = Item.find(params[:item_id2])
      @item3 = Item.find(params[:item_id3])
      study = Study.find(@item1.study_id)
      
      if study.n_way != 3
        redirect_to(studies_path)
        return
      end
    
      if @item1 == @item2 || @item2 == @item3 || @item1 == @item3 || @item1.study_id != @item2.study_id || @item1.study_id != @item3.study_id || study.active == false
        redirect_to(studies_path)
        return
      end
    
      @study_id = study.id
      @study_name = study.name
      @ncomparisons = Comparison.where(user_id: session[:user_id], study_id: study.id).size
    rescue
      redirect_to(studies_path)
    end
  end
  
  # If authenticated, and if items are valid and study is active, 
  # and if ranks are valid, 
  # record two-way comparison in database.
  def two_way
    begin
      item1 = Item.find(params[:item_id1])
      item2 = Item.find(params[:item_id2])
      study = Study.find(item1.study_id)
      
      if Comparison.where(user_id: session[:user_id], time: Time.new.to_i).size > 1
        flash[:error] = "Please make your comparisons more slowly."
        redirect_to(studies_path)
        return
      end
      
      if study.n_way != 2
        redirect_to(studies_path)
        return
      end
      
      if item1 == item2 || item1.study_id != item2.study_id || study.active == false
        redirect_to(studies_path)
        return
      end
      
      if params[:rank1].to_i < 1 || params[:rank1].to_i > 2 || params[:rank2].to_i < 1 || params[:rank2].to_i > 2 || (params[:rank1].to_i == 2 && params[:rank1] == params[:rank2])
        redirect_to(studies_path)
        return
      end
      
      c = Comparison.new
      c.user_id = session[:user_id]
      c.study_id = item1.study_id
      c.time = Time.new.to_i
      c.save
      
      r1 = Rank.new
      r1.comparison_id = c.id
      r1.item_id = item1.id
      r1.rank = params[:rank1].to_i
      r1.save
      
      r2 = Rank.new
      r2.comparison_id = c.id
      r2.item_id = item2.id
      r2.rank = params[:rank2].to_i
      r2.save
      
      redirect_to(assign_comparison_path(item1.study_id))
    rescue
      redirect_to(studies_path)
    end
  end
  
  # If authenticated, and if items are valid and study is active, 
  # and if ranks are valid, 
  # record three-way comparison in database.
  def three_way
    begin
      item1 = Item.find(params[:item_id1])
      item2 = Item.find(params[:item_id2])
      item3 = Item.find(params[:item_id3])
      study = Study.find(item1.study_id)
      
      if Comparison.where(user_id: session[:user_id], time: Time.new.to_i).size > 1
        flash[:error] = "Please make your comparisons more slowly."
        redirect_to(studies_path)
        return
      end
      
      if study.n_way != 3
        redirect_to(studies_path)
        return
      end
      
      if item1 == item2 || item2 == item3 || item1 == item3 || item1.study_id != item2.study_id || item1.study_id != item3.study_id || study.active == false
        redirect_to(studies_path)
        return
      end
      
      if params[:rank1].to_i < 1 || params[:rank1].to_i > 3 || params[:rank2].to_i < 1 || params[:rank2].to_i > 3 || params[:rank3].to_i < 1 || params[:rank3].to_i > 3
        redirect_to(studies_path)
        return
      end
      
      rank1 = params[:rank1].to_i
      rank2 = params[:rank2].to_i
      rank3 = params[:rank3].to_i
      
      if rank1 > 1 && rank2 > 1 && rank3 > 1
        rank1 = rank1 - 1
        rank2 = rank2 - 1
        rank3 = rank3 - 1
      end
      
      if rank1 > 1 && rank2 > 1 && rank3 > 1
        rank1 = rank1 - 1
        rank2 = rank2 - 1
        rank3 = rank3 - 1
      end
      
      if rank1 != 2 && rank2 != 2 && rank3 != 2
        if rank1 == 3
          rank1 = 2
        end
        if rank2 == 3
          rank2 = 2
        end
        if rank3 == 3
          rank3 = 2
        end
      end
      
      c = Comparison.new
      c.user_id = session[:user_id]
      c.study_id = item1.study_id
      c.time = Time.new.to_i
      c.save
      
      r1 = Rank.new
      r1.comparison_id = c.id
      r1.item_id = item1.id
      r1.rank = rank1.to_i
      r1.save
      
      r2 = Rank.new
      r2.comparison_id = c.id
      r2.item_id = item2.id
      r2.rank = rank2.to_i
      r2.save
      

app/views/comparisons/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1>Which one is better?</h1>
	<h4><%= @study_name %>: You have made <%= @ncomparisons %> two-way comparisons in this category.</h4>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
	  <div class="row">
        <div class="col-md-6">
		  <% if @item1.link %>
	        <h3 class="text-center"><%= link_to @item1.name, @item1.link, {target: "_blank"} %></a></h3>
	      <% else %>
		    <h3 class="text-center"><%= @item1.name %></a></h3>
		  <% end %>
	      <br>
		  <% if @item1.image %>
  		    <div class="row">
  			  <div class="col-md-3">
  			    <a href="<%= @item1.image %>" target="_blank" class="thumbnail">
  			      <img src="<%= @item1.image %>">
  			    </a>
  			  </div>
  	          <div class="col-md-9">
  	            <%= @item1.description %>
  		      </div>
  		    </div>
		  <% else %>
		    <%= @item1.description %>
		  <% end %>
	    </div>
	    <div class="col-md-6">
	      <% if @item2.link %>
	        <h3 class="text-center"><%= link_to @item2.name, @item2.link, {target: "_blank"} %></a></h3>
		  <% else %>
		    <h3 class="text-center"><%= @item2.name %></a></h3>
		  <% end %>
	      <br>
		  <% if @item2.image %>
  		    <div class="row">
  	          <div class="col-md-9">
  	            <%= @item2.description %>
  		      </div>
  			  <div class="col-md-3">
  			    <a href="<%= @item2.image %>" target="_blank" class="thumbnail">
  			      <img src="<%= @item2.image %>">
  			    </a>
  			  </div>
  		    </div>
		  <% else %>
		    <%= @item2.description %>
		  <% end %>
	    </div>
	  </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 text-center">
    <%= link_to raw("<button class=\"btn btn-success btn-lg\">&larr; This one!</button>"), two_way_comparison_path(@item1.id, 1, @item2.id, 2) %>
    <%= link_to raw("<button class=\"btn btn-primary btn-lg\">Not sure.</button>"), two_way_comparison_path(@item1.id, 1, @item2.id, 1) %>
    <%= link_to raw("<button class=\"btn btn-success btn-lg\">This one! &rarr;</button>"), two_way_comparison_path(@item1.id, 2, @item2.id, 1) %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/comparisons/show_test.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h1>How would you compare these? Ties are OK.</h1>
	<h4><%= @study_name %></h4>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
	  <div class="row">
        <div class="col-md-4">
		  <% if @item1.link %>
	        <h3 class="text-center"><%= link_to @item1.name, @item1.link, {target: "_blank"} %></a></h3>
	      <% else %>
		    <h3 class="text-center"><%= @item1.name %></a></h3>
		  <% end %>
	      <br>
	      <%= @item1.description %>
	    </div>
	    <div class="col-md-4">
	      <% if @item1.link %>
	        <h3 class="text-center"><%= link_to @item2.name, @item2.link, {target: "_blank"} %></a></h3>
		  <% else %>
		    <h3 class="text-center"><%= @item2.name %></a></h3>
		  <% end %>
	      <br>
	      <%= @item2.description %>
	    </div>
	    <div class="col-md-4">
	      <% if @item3.link %>
	        <h3 class="text-center"><%= link_to @item3.name, @item3.link, {target: "_blank"} %></a></h3>
		  <% else %>
		    <h3 class="text-center"><%= @item3.name %></a></h3>
		  <% end %>
	      <br>
	      <%= @item3.description %>
	    </div>
	  </div>
	  <br>
	  <div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-2">
  		  <select class="form-control" name="rank1" form="threeway">
  		    <option value="1">First</option>
  		    <option value="2">Second</option>
  		    <option value="3">Third</option>
  		  </select>
	    </div>
		<div class="col-md-2"></div>
		<div class="col-md-2">
  		  <select class="form-control" name="rank2" form="threeway">
  		    <option value="1">First</option>
  		    <option value="2">Second</option>
  		    <option value="3">Third</option>
  		  </select>
	    </div>
		<div class="col-md-2"></div>
		<div class="col-md-2">
  		  <select class="form-control" name="rank3" form="threeway">
  		    <option value="1">First</option>
  		    <option value="2">Second</option>
  		    <option value="3">Third</option>
  		  </select>
	    </div>
		<div class="col-md-1"></div>
	  </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 text-center">
    <button class="btn btn-primary btn-lg">Submit!</button>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/comparisons/show_three_way.html.erb
<%= javascript_include_tag 'twcscript' %>

<div class="row">
  <div class="col-md-12 text-center">
    <h3>How would you compare these?</h3>
	<% if @ncomparisons == 1 %>
	  <h5><%= @study_name %>: You have made <%= @ncomparisons %> three-way comparison in this study.</h5>
	<% else %>
	  <h5><%= @study_name %>: You have made <%= @ncomparisons %> three-way comparisons in this study.</h5>
	<% end %>
	<% if @ncomparisons > 0 %>
	  <%= link_to raw("<button type=\"button\" class=\"btn btn-danger btn-sm\">undo previous comparison</button>"), undo_comparison_path(@study_id), {accesskey: "u"} %>
	<% end %>
	<button id="restart" type="button" class="btn btn-danger btn-sm" accesskey="r">reset current comparison</button>
  </div>
</div>
<br>
<%= form_tag three_way_comparison_path(@item1.id, @item2.id, @item3.id), method: "get" do %>
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
	    <div class="row">
          <div class="col-md-4">
		    <% if @item1.link %>
	          <h4 class="text-center"><%= link_to @item1.name, @item1.link, {target: "_blank"} %></a></h4>
	        <% else %>
		      <h4 class="text-center"><%= @item1.name %></a></h4>
		    <% end %>
		  </div>
          <div class="col-md-4">
		    <% if @item2.link %>
	          <h4 class="text-center"><%= link_to @item2.name, @item2.link, {target: "_blank"} %></a></h4>
	        <% else %>
		      <h4 class="text-center"><%= @item2.name %></a></h4>
		    <% end %>
		  </div>
          <div class="col-md-4">
		    <% if @item3.link %>
	          <h4 class="text-center"><%= link_to @item3.name, @item3.link, {target: "_blank"} %></a></h4>
	        <% else %>
		      <h4 class="text-center"><%= @item3.name %></a></h4>
		    <% end %>
		  </div>
	    </div>
	    <br>
		<div class="row">
		  <div class="col-md-4">
			<% if @item1.image %>
		      <a href="<%= @item1.image %>" target="_blank" class="thumbnail" style="width:45%;float:left;margin-right:10px;margin-bottom:5px;">
		        <img src="<%= @item1.image %>">
		      </a>
			<% end %>
			<small><%= @item1.description %></small>
		  </div>
		  <div class="col-md-4">
  			<% if @item2.image %>
  		      <a href="<%= @item2.image %>" target="_blank" class="thumbnail" style="width:45%;float:left;margin-right:10px;margin-bottom:5px;">
  		        <img src="<%= @item2.image %>">
  		      </a>
  			<% end %>
			<small><%= @item2.description %></small>
		  </div>
		  <div class="col-md-4">
  			<% if @item3.image %>
  		      <a href="<%= @item3.image %>" target="_blank" class="thumbnail" style="width:45%;float:left;margin-right:10px;margin-bottom:5px;">
  		        <img src="<%= @item3.image %>">
  		      </a>
  			<% end %>
			<small><%= @item3.description %></small>
		  </div>
		</div>
	    <input style="display:none;" type="text" name="rank1" value="0">
		<input style="display:none;" type="text" name="rank2" value="0">
		<input style="display:none;" type="text" name="rank3" value="0">
		<br>
		<div class="row">
		  <div id="item1" class="col-md-4 text-center">
			<button id="rank1" accesskey="1" type="button" class="btn btn-primary">rank first</button>
		  </div>
		  <div id="item2" class="col-md-4 text-center">
			<button id="rank2" accesskey="2" type="button" class="btn btn-primary">rank first</button>
		  </div>
		  <div id="item3" class="col-md-4 text-center">
			<button id="rank3" accesskey="3" type="button" class="btn btn-primary">rank first</button>
		  </div>
		</div>
	  </div>
	  <div class="row">
	    <div class="col-md-12 text-center">
		  <button style="display:none;" id="submit" type="submit" class="btn btn-primary" accesskey="s">submit</button>
	    </div>
	  </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12 text-center">
    <h5>Tip: <%= link_to "Use keyboard shortcuts to speed up comparisons (opens in a new tab).", keyboard_path, {target: "_blank"} %></h5>
  </div>
</div>

app/views/comparisons/show_two_way.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h3>Which one is better?</h3>
	<% if @ncomparisons == 1 %>
	  <h5><%= @study_name %>: You have made <%= @ncomparisons %> two-way comparison in this study.</h5>
	<% else %>
	  <h5><%= @study_name %>: You have made <%= @ncomparisons %> two-way comparisons in this study.</h5>
	<% end %>
	<% if @ncomparisons > 0 %>
	  <%= link_to raw("<button type=\"button\" class=\"btn btn-danger btn-sm\">undo previous comparison</button>"), undo_comparison_path(@study_id), {accesskey: "u"} %>
	<% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
	  <div class="row">
        <div class="col-md-6">
		  <% if @item1.link %>
	        <h4 class="text-center"><%= link_to @item1.name, @item1.link, {target: "_blank"} %></a></h4>
	      <% else %>
		    <h4 class="text-center"><%= @item1.name %></a></h4>
		  <% end %>
	      <br>
		  <% if @item1.image %>
	        <a href="<%= @item1.image %>" target="_blank" class="thumbnail" style="width:30%;float:left;margin-right:10px;margin-bottom:5px;">
	          <img src="<%= @item1.image %>">
	        </a>
		  <% end %>
		  <small><%= @item1.description %></small>
	    </div>
	    <div class="col-md-6">
	      <% if @item2.link %>
	        <h4 class="text-center"><%= link_to @item2.name, @item2.link, {target: "_blank"} %></a></h4>
		  <% else %>
		    <h4 class="text-center"><%= @item2.name %></a></h4>
		  <% end %>
	      <br>
		  <% if @item2.image %>
	        <a href="<%= @item2.image %>" target="_blank" class="thumbnail" style="width:30%;float:right;margin-left:10px;margin-bottom:5px;">
	          <img src="<%= @item2.image %>">
	        </a>
		  <% end %>
		  <small><%= @item2.description %></small>
	    </div>
	  </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 text-center">
    <%= link_to raw("<button type=\"submit\" class=\"btn btn-success\">&larr; This one!</button>"), two_way_comparison_path(@item1.id, 1, @item2.id, 2), {accesskey: "1"} %>
    <%= link_to raw("<button type=\"submit\" class=\"btn btn-primary\">Not sure.</button>"), two_way_comparison_path(@item1.id, 1, @item2.id, 1), {accesskey: "n"} %>
    <%= link_to raw("<button type=\"submit\" class=\"btn btn-success\">This one! &rarr;</button>"), two_way_comparison_path(@item1.id, 2, @item2.id, 1), {accesskey: "2"} %>
  </div>
  <div class="col-md-3"></div>
</div>
<div class="row">
  <div class="col-md-12 text-center">
    <h5>Tip: <%= link_to "Use keyboard shortcuts to speed up comparisons (opens in a new tab).", keyboard_path, {target: "_blank"} %></h5>
  </div>
</div>