config/routes.rb
Rails.application.routes.draw do
  
  root to: "users#index"
  
  get '/users' => 'users#index', as: 'users'
  get '/users/create' => 'users#create', as: 'create_user'
  get '/users/email' => 'users#email', as: 'email_user'
  get '/users/login/:user_guid' => 'users#login', as: 'login_user'
  get '/users/logout' => 'users#logout', as: 'logout_user'
  get '/users/edit/:user_id' => 'users#edit', as: 'edit_user'
  get '/users/modify/:user_id' => 'users#modify', as: 'modify_user'
  
  get '/info' => 'info#index', as: 'info'
  
  get '/comparitor' => 'comparitor#index', as: 'comparitor'
  
  get '/studies' => 'studies#index', as: 'studies'
  get '/studies/search' => 'studies#search', as: 'search_study'
  get '/studies/new' => 'studies#new', as: 'new_study'
  get '/studies/manage' => 'studies#manage', as: 'manage_study'
  get '/studies/duplicate' => 'studies#duplicate', as: 'duplicate_study'
  get '/studies/show/:study_id' => 'studies#show', as: 'show_study'
  get '/studies/edit/:study_id' => 'studies#edit', as: 'edit_study'
  get '/studies/rename/:study_id' => 'studies#rename', as: 'rename_study'
  get '/studies/activate/:study_id/:n_way' => 'studies#activate', as: 'activate_study'
  get '/studies/publicize/:study_id' => 'studies#publicize', as: 'publicize_study'
  get '/studies/hide/:study_id' => 'studies#hide', as: 'hide_study'
  get '/studies/destroy/:study_id' => 'studies#destroy', as: 'destroy_study'
  get '/studies/add_to/:study_id' => 'studies#add_to', as: 'add_to_study'
  get '/studies/import_to/:study_id' => 'studies#import_to', as: 'import_to_study'
  get '/studies/remove_from/:study_id' => 'studies#remove_from', as: 'remove_from_study'
  get '/studies/export_items/:study_id' => 'studies#export_items', as: 'export_items_study'
  get '/studies/export_comparisons/:study_id' => 'studies#export_comparisons', as: 'export_comparisons_study'
  get '/studies/export_both/:study_id' => 'studies#export_both', as: 'export_both_study'
  
  get '/comparisons/assign/:study_id' => 'comparisons#assign', as: 'assign_comparison'
  get '/comparisons/show_two_way/:item_id1/:item_id2' => 'comparisons#show_two_way', as: 'show_two_way_comparison'
  get '/comparisons/show_three_way/:item_id1/:item_id2/:item_id3' => 'comparisons#show_three_way', as: 'show_three_way_comparison'
  get '/comparisons/two_way/:item_id1/:rank1/:item_id2/:rank2' => 'comparisons#two_way', as: 'two_way_comparison'
  get '/comparisons/three_way/:item_id1/:item_id2/:item_id3' => 'comparisons#three_way', as: 'three_way_comparison'
  get '/comparisons/undo/:study_id' => 'comparisons#undo', as: 'undo_comparison'
  
  get '/keyboard' => 'keyboard#index', as: 'keyboard'
  
  get '*path' => redirect("/")
  

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
  validates :guid, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: [:edit, :modify]
  
  # If user is not properly authenticated, 
  # e.g., if the user has no GUID, 
  # if the GUID does not match the user ID in the session,
  # or the GUID does not match the user ID in the parameter, 
  # then log the user out.
  def authenticate
    begin
      if !session[:user_guid]
        redirect_to(root_path)
      elsif session[:user_guid] != User.find_by(id: session[:user_id].to_i).guid
        redirect_to(logout_user_path)
      elsif session[:user_guid] != User.find_by(id: params[:user_id].to_i).guid
        redirect_to(logout_user_path)
      end
    rescue
      redirect_to(logout_user_path)
    end
  end
  
  # If user is not logged in, display login page.
  # Otherwise, redirect to the list of active studies.
  def index
    if session[:user_guid]
      redirect_to(comparitor_path)
    end
  end
  
  # If user already exists, redirect to email path. 
  # Otherwise, present the create account form.
  def create
    if params[:user_email] == ""
      flash[:error] = "Please enter a valid email address."
      redirect_to(root_path)
      return
    end
    
    @email = params[:user_email]
    
    begin
      u = User.find_by(email: @email)
      if u
        redirect_to(email_user_path(user_email: @email))
        return
      end
    rescue
      flash[:error] = "Please enter a valid email address."
      redirect_to(root_path)
    end
  end
  
  # If email address valid, create a new user if necessary.
  # Then, assign the user a new GUID and send a login link via email.
  def email
    net0 = IPAddr.new("128.10.0.0/16")
    net1 = IPAddr.new("128.46.0.0/16")
    net2 = IPAddr.new("128.210.0.0/16")
    net3 = IPAddr.new("128.211.0.0/16")
    net4 = IPAddr.new("204.52.32.0/19")
    net5 = IPAddr.new("192.5.40.0/24")
    net6 = IPAddr.new("192.5.101.0/24")
    net7 = IPAddr.new("192.5.102.0/24")
    net8 = IPAddr.new("192.31.0.0/24")
    net9 = IPAddr.new("192.168.0.0/16")
    net10 = IPAddr.new("127.0.0.1/32")
        
    if !(net0 === request.remote_ip || net1 === request.remote_ip || net2 === request.remote_ip || net3 === request.remote_ip || net4 === request.remote_ip || net5 === request.remote_ip || net6 === request.remote_ip || net7 === request.remote_ip || net8 === request.remote_ip || net9 === request.remote_ip || net10 === request.remote_ip)
      flash[:error] = "Please log in on the Purdue West Lafayette campus."
      redirect_to(root_path)
      return
    end
    
    if params[:user_email] == ""
      flash[:error] = "Please enter a valid email address."
      redirect_to(root_path)
      return
    end
    
    @email = params[:user_email]
    
    begin
      u = User.find_by(email: @email)
      if u
        u.guid = SecureRandom.uuid
        u.save
      else
        if params[:user_name] == ""
          flash[:error] = "Please enter a valid first name."
          redirect_to(create_user_path(user_email: @email))
          return
        end
        
        if !params[:check] || params[:check].length < 3
          flash[:error] = "You must agree to all checkboxes in order to create an account."
          redirect_to(create_user_path(user_email: @email))
          return
        end
        
        u = User.new
        u.email = @email
        u.name = params[:user_name]
        u.guid = SecureRandom.uuid
        u.save
      end
      
      Mailer.send_login_email(u, "http://" + request.host_with_port + login_user_path(u.guid)).deliver
    rescue
      flash[:error] = "Please enter a valid email address."
      redirect_to(root_path)
    end
  end
  
  # If GUID is valid, store user's ID, email, and GUID in the session.
  # Otherwise, redirect to login page.
  def login
    begin
      u = User.find_by(guid: params[:user_guid])
      session[:user_id] = u.id
      session[:user_email] = u.email
      session[:user_guid] = u.guid
      session[:user_name] = u.name
    rescue
      flash[:error] = "Please log in again, and follow the link sent to you via email."
    ensure
      redirect_to(root_path)
    end
  end
  
  # Reset GUID if possible. 
  # Then, clear the information from the session.
  def logout
    begin
      u = User.find(session[:user_id])
      u.guid = SecureRandom.uuid
      u.save
    rescue
      
    ensure
      flash[:notice] = "When you log in next time, we'll send you a new login link via email."
    
      session[:user_id] = nil
      session[:user_email] = nil
      session[:user_guid] = nil
      session[:user_name] = nil
      
      redirect_to(root_path)
    end
  end
  
  # If authenticated, display edit account page, 
  # including user statistics.
  def edit
    begin
      @ncomparisons = Comparison.where(user_id: params[:user_id]).size
    rescue
      redirect_to(root_path)
    end
  end
  
  # If authenticated and new email address and name are valid, 
  # then modify account's email address and name.
  def modify
    begin
      u = User.find(params[:user_id])
      unless params[:user_email] == ""
        u.email = params[:user_email]
        session[:user_email] = params[:user_email]
      end
      unless params[:user_name] == ""
        u.name = params[:user_name]
        session[:user_name] = params[:user_name]
      end
      u.save
    rescue
      flash[:error] = "Please enter a valid email address."
    ensure
      redirect_to(edit_user_path(session[:user_id]))
    end
  end
end

app/views/users/create.html.erb
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <div class="jumbotron">
      <h1 class="text-center">The Comparitor</h1>
	  <br>
	  <%= form_tag email_user_path, method: "get" do %>
	    <h4>Please create a new account.</h4>
	    <br>
  	    <div class="input-group input-group-md">
  	      <span class="input-group-addon">email</span>
  	      <input name="user_email" type="text" class="form-control" value="<%= @email %>">
	    </div>
  	    <br>
  	    <div class="input-group input-group-md">
  	      <span class="input-group-addon">first name</span>
  	      <input name="user_name" type="text" class="form-control" placeholder="First">
	    </div>
		<br>
		<h4><%= link_to "Click here to read about The Comparitor experiment (opens in a new tab).", info_path, {target: "_blank"} %></h4>
		<h6><%= check_box_tag "check[]", 0 %> I am at least 18 years old.</h6>
		<h6><%= check_box_tag "check[]", 1 %> I am not in prison, and I am not involved in a court-ordered program or a community corrections program.</h6>
		<h6><%= check_box_tag "check[]", 2 %> I understand and accept that my data will be collected for research purposes.</h6>
		<br>
		<div class="text-center">
          <button type="submit" class="btn btn-primary btn-lg">create account!</button>
		</div>
	  <% end %>
    </div>
  </div>
  
  <div class="col-md-2"></div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-5">
	<h1>My Account</h1>
	<br>
    <%= form_tag modify_user_path, method: "get" do %>
	  <div class="input-group input-group">
	    <span class="input-group-addon">email</span>
	    <input name="user_email" type="text" class="form-control" value="<%= session[:user_email] %>">
      </div>
	  <br>
	  <div class="input-group input-group">
	    <span class="input-group-addon">first name</span>
	    <input name="user_name" type="text" class="form-control" value="<%= session[:user_name] %>">
      </div>
	  <br>
      <button type="submit" class="btn btn-primary">update account information</button>
    <% end %>
  </div>
  <div class="col-md-1"></div>
  <div class="col-md-5">
	<h1>My Statistics</h1>
	<br>
	<% if @ncomparisons == 1 %>
	  <h4>You have made <%= @ncomparisons %> comparison.</h4>
	<% else %>
	  <h4>You have made <%= @ncomparisons %> comparisons.</h4>
	<% end %>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/users/email.html.erb
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <div class="jumbotron text-center">
      <h1>The Comparitor</h1>
	  <br>
	  <h4>An email has been sent to <%= @email %> with a link to log in.</h4>
    </div>
  </div>
  
  <div class="col-md-2"></div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-2"></div>
  
  <div class="col-md-8">
    <div class="jumbotron text-center">
      <h1>The Comparitor</h1>
	  <br>
	  <%= form_tag create_user_path, method: "get" do %>
  	    <div class="input-group input-group-lg">
  	      <span class="input-group-addon">email</span>
  	      <input name="user_email" type="text" class="form-control" placeholder="email@example.com">
	    </div>
  	    <br>
        <button type="submit" class="btn btn-primary btn-lg">log in or create account</button>
	  <% end %>
    </div>
  </div>
  
  <div class="col-md-2"></div>
</div>