config/routes.rb
Rails.application.routes.draw do
  
  root to: "users#index"
  
  get '/users' => 'users#index', as: 'users'
  get '/users/create' => 'users#create', as: 'create_user'
  get '/users/email' => 'users#email', as: 'email_user'
  get '/users/login/:user_guid' => 'users#login', as: 'login_user'
  get '/users/logout' => 'users#logout', as: 'logout_user'
  get '/users/edit/:user_id' => 'users#edit', as: 'edit_user'
  get '/users/modify/:user_id' => 'users#modify', as: 'modify_user'
  
  get '/info' => 'info#index', as: 'info'
  
  get '/comparitor' => 'comparitor#index', as: 'comparitor'
  
  get '/studies' => 'studies#index', as: 'studies'
  get '/studies/search' => 'studies#search', as: 'search_study'
  get '/studies/new' => 'studies#new', as: 'new_study'
  get '/studies/manage' => 'studies#manage', as: 'manage_study'
  get '/studies/duplicate' => 'studies#duplicate', as: 'duplicate_study'
  get '/studies/show/:study_id' => 'studies#show', as: 'show_study'
  get '/studies/edit/:study_id' => 'studies#edit', as: 'edit_study'
  get '/studies/rename/:study_id' => 'studies#rename', as: 'rename_study'
  get '/studies/activate/:study_id/:n_way' => 'studies#activate', as: 'activate_study'
  get '/studies/publicize/:study_id' => 'studies#publicize', as: 'publicize_study'
  get '/studies/hide/:study_id' => 'studies#hide', as: 'hide_study'
  get '/studies/destroy/:study_id' => 'studies#destroy', as: 'destroy_study'
  get '/studies/add_to/:study_id' => 'studies#add_to', as: 'add_to_study'
  get '/studies/import_to/:study_id' => 'studies#import_to', as: 'import_to_study'
  get '/studies/remove_from/:study_id' => 'studies#remove_from', as: 'remove_from_study'
  get '/studies/export_items/:study_id' => 'studies#export_items', as: 'export_items_study'
  get '/studies/export_comparisons/:study_id' => 'studies#export_comparisons', as: 'export_comparisons_study'
  get '/studies/export_both/:study_id' => 'studies#export_both', as: 'export_both_study'
  
  get '/comparisons/assign/:study_id' => 'comparisons#assign', as: 'assign_comparison'
  get '/comparisons/show_two_way/:item_id1/:item_id2' => 'comparisons#show_two_way', as: 'show_two_way_comparison'
  get '/comparisons/show_three_way/:item_id1/:item_id2/:item_id3' => 'comparisons#show_three_way', as: 'show_three_way_comparison'
  get '/comparisons/two_way/:item_id1/:rank1/:item_id2/:rank2' => 'comparisons#two_way', as: 'two_way_comparison'
  get '/comparisons/three_way/:item_id1/:item_id2/:item_id3' => 'comparisons#three_way', as: 'three_way_comparison'
  get '/comparisons/undo/:study_id' => 'comparisons#undo', as: 'undo_comparison'
  
  get '/keyboard' => 'keyboard#index', as: 'keyboard'
  
  get '*path' => redirect("/")
  

end

app/models/study.rb
class Study < ActiveRecord::Base
  validates :name, presence: true
  validates :user_id, presence: true
  validates :n_way, presence: true
  validates :originator, presence: true
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :authenticate
  
  # If user is not properly authenticated, 
  # e.g., if the user has no GUID, 
  # or if the GUID does not match the user ID in the session,
  # then log the user out.
  def authenticate
    begin
      if !session[:user_guid]
        redirect_to(root_path)
      elsif session[:user_guid] != User.find_by(id: session[:user_id].to_i).guid
        redirect_to(logout_user_path)
      end
    rescue
      redirect_to(logout_user_path)
    end
  end
  
  # If authenticated, display page with list of active and public studies.
  def index
    @studies = Study.where(active: true, public: true)
    @studies = @studies.reverse_each
  end
  
  # If authenticated, display page with list of active and public studies 
  # according to the search results.
  def search
    begin
      if params[:email] != "" && params[:study_name] != ""
        @header = "Studies: #{params[:study_name]} by #{params[:email]}"
        @studies = Study.where(originator: params[:email], name: params[:study_name], active: true, public: true)
      elsif params[:email] != ""
        @header = "Studies: #{params[:email]}"
        @studies = Study.where(originator: params[:email], active: true, public: true)
      elsif params[:study_name] != ""
        @header = "Studies: #{params[:study_name]}"
        @studies = Study.where(name: params[:study_name], active: true, public: true)
      else
        redirect_to(studies_path)
        return
      end
      @studies = @studies.reverse_each
    rescue
      redirect_to(studies_path)
    end
  end
  
  # If authenticated, display page to manage user's studies.
  def manage
    begin
      @studies = Study.where(user_id: session[:user_id])
      @studies = @studies.reverse_each
    end
  end
  
  # If authenticated, and if study is active or belongs to the user, 
  # display items in some study.
  def show
    begin
      @study = Study.find(params[:study_id])
      @items = Item.where(study_id: params[:study_id])
      @items = @items.reverse_each
      
      if @study.active == false && @study.user_id != session[:user_id]
        redirect_to(studies_path)
      end
    rescue
      redirect_to(studies_path)
    end
  end
  
  # If authenticated, create new study.
  def new
    begin
      s = Study.new
      s.name = params[:study_name]
      s.originator = session[:user_email]
      s.user_id = session[:user_id]
      s.active = false
      s.public = false
      s.n_way = 2
      unless s.save
        flash[:error] = "Please enter a valid study name."
      end
    rescue
      
    ensure
      redirect_to(manage_study_path)
    end
  end
  
  # If authenaticated, and if study belongs to user, 
  # duplicate an existing study.
  def duplicate
    begin
      study = Study.find(params[:study_id])
      if study.user_id != session[:user_id]
        redirect_to(manage_study_path)
        return
      end
      
      unless params[:study_name] && params[:study_name] != ""
        flash[:error] = "Please enter a valid name for the duplicate study."
        redirect_to(manage_study_path)
        return
      end
      
      s = Study.new
      s.name = params[:study_name]
      s.originator = session[:user_email]
      s.user_id = session[:user_id]
      s.active = false
      s.public = false
      s.n_way = 2
      s.save
      
      items = Item.where(study_id: params[:study_id])
      items.each do |item|
        i = Item.new
        i.study_id = s.id
        i.name = item.name
        i.description = item.description
        i.link = item.link
        i.image = item.image
        i.save
      end
      
      redirect_to(manage_study_path)
    rescue
      redirect_to(manage_study_path)
    end
  end
  
  # If authenticated, if study belongs to user, and if study is inactive
  # display page to edit study.
  def edit
    begin
      @study = Study.find(params[:study_id])
      if @study.user_id != session[:user_id] || @study.active == true
        redirect_to(manage_study_path)
        return
      end
      
      @items = Item.where(study_id: params[:study_id])
      @items = @items.reverse_each
    rescue
      redirect_to(manage_study_path)
    end
  end
  
  # If authenicated, if study belongs to user, and if study is inactive, 
  # rename study.
  def rename
    begin
      study = Study.find(params[:study_id])
      unless study.user_id != session[:user_id] || study.active == true
        study.name = params[:study_name]
        study.save
      end
    rescue

    ensure
      redirect_to(edit_study_path(params[:study_id]))
    end
  end
  
  # If authenticated, and if study belongs to user, and if study has enough items,
  # activate study.
  def activate
    begin
      study = Study.find(params[:study_id])
      
      if study.user_id != session[:user_id]
        return
      end
      
      n = params[:n_way].to_i
      if n != 2 && n != 3
        return 
      end
      
      if Item.where(study_id: params[:study_id]).size < n
        flash[:error] = "A #{n}-way comparison study must have at least #{n} items before activation."
        return
      end
      
      study.n_way = n
      study.active = true
      study.save
      
      flash[:notice] = "Your study is currently private. Only people with your study's \"link to share\" can access your study. To publish your study to the homepage, change your study's privacy from \"private\" to \"public.\""
    rescue
      
    ensure
      redirect_to(manage_study_path)
    end
  end
  
  # If authenticated, and if study belongs to user, and if study is active, 
  # make study public.
  def publicize
    begin
      study = Study.find(params[:study_id])
      
      if study.user_id == session[:user_id] && study.active
        study.public = true
        study.save
      end
    rescue
      
    ensure
      redirect_to(manage_study_path)
    end
  end
  
  # If authenticated, and if study belongs to user, and if study is active, 
  # hide study.
  def hide
    begin
      study = Study.find(params[:study_id])
      
      if study.user_id == session[:user_id] && study.active
        study.public = false
        study.save
      end
    rescue
      
    ensure
      redirect_to(manage_study_path)
    end
  end
  
  # If authenticated, and if study belongs to user, 
  # destroy study, its items, and its comparisons.
  def destroy
    begin
      study = Study.find(params[:study_id])
      items = Item.where(study_id: params[:study_id])
      comparisons = Comparison.where(study_id: params[:study_id])
      
      unless study.user_id != session[:user_id]
        items.each do |item|
          item.destroy
        end
        
        comparisons.each do |comparison|
          ranks = Rank.where(comparison_id: comparison.id)
          ranks.each do |rank|
            rank.destroy
          end
          comparison.destroy
        end
        
        study.destroy
      end 
    rescue
      
    ensure
      redirect_to(manage_study_path)
    end
  end
  
  # If authenicated, if study belongs to user, and if study is inactive, 
  # add item to study.
  def add_to
    begin
      study = Study.find(params[:study_id])
      unless study.user_id != session[:user_id] || study.active == true
        i = Item.new
        i.study_id = params[:study_id]
        i.name = params[:item_name]
        i.description = params[:item_description]
        unless i.save
          flash[:error] = "Please enter a valid item name and description."
        end
      end
    rescue

    ensure
      redirect_to(edit_study_path(params[:study_id]))
    end
  end
  
  # If authenicated, if study belongs to user, and if study is inactive, 
  # import items in category to study.
  def import_to
    begin
      study = Study.find(params[:study_id])
      
      unless study.user_id != session[:user_id] || study.active == true
        sparql = SPARQL::Client.new("http://dbpedia.org/sparql")
        
        category = params[:category_name].gsub ' ', '_'
        
        items = sparql.query("SELECT ?name ?description ?link ?image
        WHERE {
        ?name <http://purl.org/dc/terms/subject> <http://dbpedia.org/resource/Category:#{category}> .
        ?name <http://www.w3.org/2000/01/rdf-schema#comment> ?description . 
        ?name <http://xmlns.com/foaf/0.1/isPrimaryTopicOf> ?link .
        ?name <http://xmlns.com/foaf/0.1/depiction> ?image .
        FILTER (LANG(?description) = 'en')
        }")
        
        unless items.size < 1
          items.each do |item|
            description = item[:description].to_s
            link = item[:link].to_s
            image = item[:image].to_s
    
            name = link.split("\n").grep(/http:\/\/en.wikipedia.org\/wiki\/(.*)/){$1}[0]
            name = name.gsub '_', ' '
            
            i = Item.new
            i.study_id = params[:study_id]
            i.name = name
            i.description = description
            i.link = link
            i.image = image
            i.save
          end
        end
        
        items = sparql.query("SELECT ?name ?description ?link ?image
        WHERE {
        ?name <http://purl.org/dc/terms/subject> <http://dbpedia.org/resource/Category:#{category}> .
        ?name <http://www.w3.org/2000/01/rdf-schema#comment> ?description . 
        ?name <http://xmlns.com/foaf/0.1/isPrimaryTopicOf> ?link .
        FILTER (LANG(?description) = 'en')
        }")
        
        if items.size > 0
          items.each do |item|
            description = item[:description].to_s
            link = item[:link].to_s
    
            name = link.split("\n").grep(/http:\/\/en.wikipedia.org\/wiki\/(.*)/){$1}[0]
            name = name.gsub '_', ' '
            
            unless Item.where(name: name).size > 0
              i = Item.new
              i.study_id = params[:study_id]
              i.name = name
              i.description = description
              i.link = link
              i.save

app/views/studies/comparisons_and_items.csv.erb
<%= CSV.generate_line @headers %> <% @comparisons.each do |comparison| %> <%= CSV.generate_line([comparison[0], comparison[1], comparison[2], comparison[3], comparison[4], comparison[5]]) %> <% end %>

app/views/studies/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Edit Study: <%= @study.name %></h1>
  </div>
</div>
<br>
<div class="row">
  <%= form_tag rename_study_path, method: "get" do %>
    <div class="col-md-10">
      <div class="input-group">
        <span class="input-group-addon">study name</span>
        <input name="study_name" type="text" class="form-control" value="<%= @study.name %>">
      </div>
    </div>
	<div class="col-md-2">
	  <button type="submit" class="btn btn-primary">rename study</button>
	</div>
  <% end %>
</div>
<br>
<div class="row">
  <%= form_tag add_to_study_path, method: "get" do %>
    <div class="col-md-5">
      <div class="input-group">
        <span class="input-group-addon">new item</span>
        <input name="item_name" type="text" class="form-control" placeholder="name">
      </div>
    </div>
    <div class="col-md-5">
      <div class="input-group">
		<span class="input-group-addon">description</span>
        <input name="item_description" type="text" class="form-control" placeholder="description">
      </div>
    </div>
	<div class="col-md-2">
	  <button type="submit" class="btn btn-primary">add item</button>
	</div>
  <% end %>
</div>
<br>
<div class="row">
  <%= form_tag import_to_study_path, method: "get" do %>
    <div class="col-md-10">
      <div class="input-group">
        <span class="input-group-addon">import items from Wikipedia category</span>
        <input name="category_name" type="text" class="form-control" placeholder="category (case sensitive)">
      </div>
    </div>
	<div class="col-md-2">
	  <button type="submit" class="btn btn-primary">import category</button>
	</div>
  <% end %>
</div>
<br>
<div class="row">
  <div class="col-md-12">
	<div class="panel panel-default">
	  <table class="table">
		<%= form_tag remove_from_study_path, method: "get" do %>
		  <tr>
	        <th>Item</th>
		    <th>Description</th>
			<% if @items.first %>
			  <th><%= submit_tag "delete selected", :class => "btn btn-sm btn-danger" %></th>
			<% end %>
		  </tr>
		  <% @items.each do |item| %>
		    <tr>
			  <% if item.link %>
		  	    <td class="col-md-3"><%= link_to item.name, item.link, {target: "_blank"} %></td>
			  <% else %>
			    <td class="col-md-3"><%= item.name %></td>
			  <% end %>
			  <td class="col-md-8"><%= item.description %></td>
			  <td class="col-md-1 text-right">
			    <%= check_box_tag "items[]", item.id %>
			  </td>
		    </tr>
		  <% end %>
		<% end %>
	  </table>
    </div>
  </div>
</div>

app/views/studies/export_both.csv.erb
<%= CSV.generate_line @headers %> <% @comparisons.each do |comparison| %> <%= CSV.generate_line(comparison).html_safe %> <% end %>

app/views/studies/export_comparisons.csv.erb
<%= CSV.generate_line @headers %> <% @comparisons.each do |comparison| %> <%= CSV.generate_line(comparison).html_safe %> <% end %> 

app/views/studies/export_items.csv.erb
<%= CSV.generate_line @headers %> <% @items.each do |item| %> <%= CSV.generate_line([item.id, item.name]).html_safe %> <% end %>

app/views/studies/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Studies</h1>
  </div>
</div>
<br>
<div class="row">
  <%= form_tag search_study_path, method: "get" do %>
    <div class="col-md-5">
	  <div class="input-group">
	    <span class="input-group-addon">search by study name</span>
	    <input name="study_name" type="text" class="form-control" placeholder="name">
      </div>
	</div>
    <div class="col-md-5">
	  <div class="input-group">
	    <span class="input-group-addon">search by originator</span>
	    <input name="email" type="text" class="form-control" placeholder="email@example.com">
      </div>
	</div>
	<div class="col-md-2">
      <button type="submit" class="btn btn-primary">search</button>
    </div>
  <% end %>
</div>
<br>
<div class="row">
  <div class="col-md-12">
  	<div class="panel panel-default">
  	  <table class="table">
  		<tr>
  	      <th>Study</th>
		  <th>Originator</th>
		  <th>Options</th>
  		</tr>
  	    <% @studies.each do |study| %>
  	      <tr>
  			<td class="col-md-3"><%= link_to study.name, show_study_path(study.id) %></td>
			<td class="col-md-3"><%= study.originator %></td>
			<td class="col-md-6">
  			  <div class="btn-group">
				<%= link_to raw("<button type=\"button\" class=\"btn btn-sm btn-primary dropdown-toggle\">start making #{study.n_way}-way comparisons</button>"), assign_comparison_path(study.id) %>
              </div>
			</td>
  		  </tr>
  	    <% end %>
  	  </table>
    </div>
  </div>
</div>

app/views/studies/list.html.erb
<div class="row">
  <div class="col-md-12">
	<% if @email == session[:user_email] %>
      <h1><%= link_to "Studies:", studies_path %> My Studies</h1>
	<% else %>
	  <h1><%= link_to "Studies:", studies_path %> <%= @email %></h1>
	<% end %>
  </div>
</div>
<% if @email == session[:user_email] %>
  <br>
  <div class="row">
    <%= form_tag new_study_path, method: "get" do %>
      <div class="col-md-5">
        <div class="input-group">
          <span class="input-group-addon">new study</span>
          <input name="study_name" type="text" class="form-control" placeholder="Name">
        </div>
      </div>
	  <div class="col-md-7">
	    <button class="btn btn-primary">create study</button>
	  </div>
    <% end %>
  </div>
<% end %>
<br>
<div class="row">
  <div class="col-md-12">
  	<div class="panel panel-default">
  	  <table class="table">
  		<tr>
  	      <th>Study</th>
		  <th>Options</th>
  		</tr>
  	    <% @studies.each do |study| %>
  	      <tr>
  			<td class="col-md-3"><%= link_to study.name, show_study_path(study.id) %></td>
			<td class="col-md-9">
			  <% if study.user_id == session[:user_id] && study.active == false %>
  			    <div class="btn-group">
                  <%= link_to raw("<button type=\"button\" class=\"btn btn-sm btn-primary\">edit</button>"), edit_study_path(study.id) %>
                </div>
 		        <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-success dropdown-toggle" data-toggle="dropdown">
                    activate <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "activate study (you will no longer be able to edit study)", activate_study_path(study.id) %></li>
                  </ul>
                </div>
			  <% end %>
			  <% if study.active == true %>
  			    <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">
				    start comparing
				  </button>
                </div>
			  <% end %>
			  <% if study.user_id == session[:user_id] %>
 		        <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-danger dropdown-toggle" data-toggle="dropdown">
                    delete <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "delete study forever", destroy_study_path(study.id) %></li>
                  </ul>
                </div>
			  <% end %>
			</td>
  		  </tr>
  	    <% end %>
  	  </table>
    </div>
  </div>
</div>

app/views/studies/manage.html.erb
<div class="row">
  <div class="col-md-12">
	<h1>My Studies</h1>
  </div>
</div>
<br>
<div class="row">
  <%= form_tag new_study_path, method: "get" do %>
    <div class="col-md-10">
      <div class="input-group">
        <span class="input-group-addon">new study</span>
        <input name="study_name" type="text" class="form-control" placeholder="name">
      </div>
    </div>
	<div class="col-md-2">
      <button type="submit" class="btn btn-primary">create study</button>
	</div>
  <% end %>
</div>
<br>
<% if @studies.count > 0 %>
  <div class="row">
    <%= form_tag duplicate_study_path, method: "get" do %>
      <div class="col-md-8">
        <div class="input-group">
          <span class="input-group-addon">duplicate existing study</span>
          <input name="study_name" type="text" class="form-control" placeholder="name of duplicate study">
        </div>
      </div>
	  <div class="col-md-2">
	    <select class="form-control" name="study_id">
		  <% @studies.each do |study| %>
			<option value=<%= study.id %>><%= study.name %></option>
		  <% end %>
        </ul>
		</select>
	  </div>
	  <div class="col-md-2">
	    <button type="submit" class="btn btn-primary">duplicate study</button>
	  </div>
    <% end %>
  </div>
<% end %>
<br>
<div class="row">
  <div class="col-md-12">
  	<div class="panel panel-default">
  	  <table class="table">
  		<tr>
  	      <th>Study</th>
		  <th>Options</th>
		  <th>Privacy</th>
		  <th>Link to Share</th>
  		</tr>
  	    <% @studies.each do |study| %>
  	      <tr>
  			<td class="col-md-3"><%= link_to study.name, show_study_path(study.id) %></td>
			<td class="col-md-4">
			  <% if study.active == false %>
  			    <div class="btn-group">
                  <%= link_to raw("<button type=\"button\" class=\"btn btn-sm btn-primary\">edit</button>"), edit_study_path(study.id) %>
                </div>
 		        <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-success dropdown-toggle" data-toggle="dropdown">
                    activate <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "activate 2-way comparison study (you will no longer be able to edit study)", activate_study_path(study.id, 2) %></li>
                    <li><%= link_to "activate 3-way comparison study (you will no longer be able to edit study)", activate_study_path(study.id, 3) %></li>
                  </ul>
                </div>
			  <% else %>
  			    <div class="btn-group">
                  <%= link_to raw("<button type=\"button\" class=\"btn btn-sm btn-primary dropdown-toggle\">start making #{study.n_way}-way comparisons</button>"), assign_comparison_path(study.id) %>
                </div>
 		        <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-success dropdown-toggle" data-toggle="dropdown">
                    export data <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
					<li><%= link_to "list of items", export_items_study_path(format: :csv, study_id: study.id) %></li>
					<li><%= link_to "list of comparisons", export_comparisons_study_path(format: :csv, study_id: study.id) %></li>
                    <li><%= link_to "list comparisons with item names", export_both_study_path(format: :csv, study_id: study.id) %></li>
                  </ul>
                </div>
			  <% end %>
 		      <div class="btn-group">
                <button type="button" class="btn btn-sm btn-danger dropdown-toggle" data-toggle="dropdown">
                  delete <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "delete study forever", destroy_study_path(study.id) %></li>
                </ul>
              </div>
			</td>
			<td class="col-md-1">
		      <% if study.active && study.public == false %>
 		        <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">
                    private <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "make study public (study will be listed on studies page)", publicize_study_path(study.id) %></li>
                  </ul>
                </div>
			  <% elsif study.active && study.public %>
 		        <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">
                    public <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "make study private (study will not be listed on studies page)", hide_study_path(study.id) %></li>
                  </ul>
                </div>
			  <% end %>
			</td>
			<td class="col-md-3">
		      <% if study.active %>
			    <div class="input-group input-group-sm">
			      <input type="text" class="form-control" value="http://<%= request.host_with_port %><%= show_study_path(study.id) %>">
				</div>
			  <% end %>
			</td>
  		  </tr>
  	    <% end %>
  	  </table>
    </div>
  </div>
</div>

app/views/studies/name.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Studies: <%= @name %></h1>
  </div>
</div>
<br>
<div class="row">
  <%= form_tag originator_study_path, method: "get" do %>
    <div class="col-md-10">
	  <div class="input-group">
	    <span class="input-group-addon">search by originator</span>
	    <input name="email" type="text" class="form-control" placeholder="email@example.com">
      </div>
	</div>
	<div class="col-md-2">
      <button class="btn btn-primary">search</button>
    </div>
  <% end %>
</div>
<br>
<div class="row">
  <%= form_tag name_study_path, method: "get" do %>
    <div class="col-md-10">
	  <div class="input-group">
	    <span class="input-group-addon">search by name</span>
	    <input name="study_name" type="text" class="form-control" placeholder="name">
      </div>
	</div>
	<div class="col-md-2">
      <button class="btn btn-primary">search</button>
    </div>
  <% end %>
</div>
<br>
<div class="row">
  <div class="col-md-12">
  	<div class="panel panel-default">
  	  <table class="table">
  		<tr>
  	      <th>Study</th>
		  <th>Originator</th>
		  <th>Options</th>
  		</tr>
  	    <% @studies.each do |study| %>
		  <% if study.active == true %>
  	        <tr>
  			  <td class="col-md-3"><%= link_to study.name, show_study_path(study.id) %></td>
			  <td class="col-md-3"><%= study.originator %></td>
			  <td class="col-md-6">
  			    <div class="btn-group">
				  <%= link_to raw("<button type=\"button\" class=\"btn btn-sm btn-primary dropdown-toggle\">start comparing</button>"), assign_comparison_path(study.id) %>
                </div>
			  </td>
  		    </tr>
		  <% end %>
  	    <% end %>
  	  </table>
    </div>
  </div>
</div>

app/views/studies/search.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= @header %></h1>
  </div>
</div>
<br>
<div class="row">
  <%= form_tag search_study_path, method: "get" do %>
    <div class="col-md-5">
	  <div class="input-group">
	    <span class="input-group-addon">search by study name</span>
	    <input name="study_name" type="text" class="form-control" placeholder="name">
      </div>
	</div>
    <div class="col-md-5">
	  <div class="input-group">
	    <span class="input-group-addon">search by originator</span>
	    <input name="email" type="text" class="form-control" placeholder="email@example.com">
      </div>
	</div>
	<div class="col-md-2">
      <button type="submit" class="btn btn-primary">search</button>
    </div>
  <% end %>
</div>
<br>
<div class="row">
  <div class="col-md-12">
  	<div class="panel panel-default">
  	  <table class="table">
  		<tr>
  	      <th>Study</th>
		  <th>Originator</th>
		  <th>Options</th>
  		</tr>
  	    <% @studies.each do |study| %>
  	      <tr>
  			<td class="col-md-3"><%= link_to study.name, show_study_path(study.id) %></td>
			<td class="col-md-3"><%= study.originator %></td>
			<td class="col-md-6">
  			  <div class="btn-group">
				<%= link_to raw("<button type=\"button\" class=\"btn btn-sm btn-primary dropdown-toggle\">start making #{study.n_way}-way comparisons</button>"), assign_comparison_path(study.id) %>
              </div>
			</td>
  		  </tr>
  	    <% end %>
  	  </table>
    </div>
  </div>
</div>

app/views/studies/show.html.erb
<div class="row">
  <div class="col-md-12">
	<h1><%= @study.name %></h1>
	<% if @study.active %>
	  <%= link_to raw("<button type=\"button\" class=\"btn btn-primary dropdown-toggle\">start making #{@study.n_way}-way comparisons</button>"), assign_comparison_path(@study.id) %>
	<% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
	<div class="panel panel-default">
	  <table class="table">
		<tr>
	      <th>Item</th>
		  <th>Description</th>
		</tr>
		<% @items.each do |item| %>
		  <tr>
			<% if item.link %>
		  	  <td class="col-md-3"><%= link_to item.name, item.link, {target: "_blank"} %></td>
			<% else %>
			  <td class="col-md-3"><%= item.name %></td>
			<% end %>
			<td class="col-md-9"><%= item.description %></td>
		  </tr>
		<% end %>
	  </table>
    </div>
  </div>
</div>