config/routes.rb
Rails.application.routes.draw do
  
  root to: "users#index"
  
  get '/users' => 'users#index', as: 'users'
  get '/users/create' => 'users#create', as: 'create_user'
  get '/users/email' => 'users#email', as: 'email_user'
  get '/users/login/:user_guid' => 'users#login', as: 'login_user'
  get '/users/logout' => 'users#logout', as: 'logout_user'
  get '/users/edit/:user_id' => 'users#edit', as: 'edit_user'
  get '/users/modify/:user_id' => 'users#modify', as: 'modify_user'
  
  get '/info' => 'info#index', as: 'info'
  
  get '/comparitor' => 'comparitor#index', as: 'comparitor'
  
  get '/studies' => 'studies#index', as: 'studies'
  get '/studies/search' => 'studies#search', as: 'search_study'
  get '/studies/new' => 'studies#new', as: 'new_study'
  get '/studies/manage' => 'studies#manage', as: 'manage_study'
  get '/studies/duplicate' => 'studies#duplicate', as: 'duplicate_study'
  get '/studies/show/:study_id' => 'studies#show', as: 'show_study'
  get '/studies/edit/:study_id' => 'studies#edit', as: 'edit_study'
  get '/studies/rename/:study_id' => 'studies#rename', as: 'rename_study'
  get '/studies/activate/:study_id/:n_way' => 'studies#activate', as: 'activate_study'
  get '/studies/publicize/:study_id' => 'studies#publicize', as: 'publicize_study'
  get '/studies/hide/:study_id' => 'studies#hide', as: 'hide_study'
  get '/studies/destroy/:study_id' => 'studies#destroy', as: 'destroy_study'
  get '/studies/add_to/:study_id' => 'studies#add_to', as: 'add_to_study'
  get '/studies/import_to/:study_id' => 'studies#import_to', as: 'import_to_study'
  get '/studies/remove_from/:study_id' => 'studies#remove_from', as: 'remove_from_study'
  get '/studies/export_items/:study_id' => 'studies#export_items', as: 'export_items_study'
  get '/studies/export_comparisons/:study_id' => 'studies#export_comparisons', as: 'export_comparisons_study'
  get '/studies/export_both/:study_id' => 'studies#export_both', as: 'export_both_study'
  
  get '/comparisons/assign/:study_id' => 'comparisons#assign', as: 'assign_comparison'
  get '/comparisons/show_two_way/:item_id1/:item_id2' => 'comparisons#show_two_way', as: 'show_two_way_comparison'
  get '/comparisons/show_three_way/:item_id1/:item_id2/:item_id3' => 'comparisons#show_three_way', as: 'show_three_way_comparison'
  get '/comparisons/two_way/:item_id1/:rank1/:item_id2/:rank2' => 'comparisons#two_way', as: 'two_way_comparison'
  get '/comparisons/three_way/:item_id1/:item_id2/:item_id3' => 'comparisons#three_way', as: 'three_way_comparison'
  get '/comparisons/undo/:study_id' => 'comparisons#undo', as: 'undo_comparison'
  
  get '/keyboard' => 'keyboard#index', as: 'keyboard'
  
  get '*path' => redirect("/")
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Comparitor</title>
  
  <%= favicon_link_tag 'favicon.ico' %>
  
  <%= stylesheet_link_tag "cerulean", :media => "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
	  <%= link_to "The Comparitor", root_path, {class: "navbar-brand"}%>
	</div>
	
	<% if session[:user_id] && session[:user_email] %>
	  <ul class="nav navbar-nav navbar-left">
		<li><%= link_to "Studies", studies_path %></li>
		<li><%= link_to "My Studies", manage_study_path %></li>
	  </ul>
      <ul class="nav navbar-nav navbar-right">
	    <li><p class="navbar-text">Welcome, <%= session[:user_name] %>!</p></li>
        <li><%= link_to "My Account", edit_user_path(session[:user_id]) %></li>
	    <li><%= link_to "Logout", logout_user_path %></li>
	  </ul>
	<% end %>
  </div>
</nav>

<div class="container">
  <% if flash[:error] %>
    <div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
  <% elsif flash[:notice] %>
  	<div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
  <% end %>
  
  <%= yield %>
</div>

<br>

<div class="container text-center">
  <small><%= link_to "Click here to read about The Comparitor experiment (opens in a new tab).", info_path, {target: "_blank"} %></small>
</div>

</body>
</html>